#pragma warning disable 1591

// Copyright 2008, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 2.0.0.0
// Schema file: schema.xsd
// Creation Date: 3/10/2019 20:48:24
//--------------------------------------------------------------

using System;
using System.Xml.Serialization;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Schema;
using System.ComponentModel;

namespace Test
{

	public struct Declarations
	{
		public const string SchemaVersion = "";
	}




	[XmlRoot(ElementName="shiporder",IsNullable=false),Serializable]
	public class shiporder
	{

		[XmlIgnore]
		private string _orderid;
		
		[XmlAttribute(AttributeName="orderid",DataType="string")]
		public string orderid
		{ 
			get { return _orderid; }
			set { _orderid = value; }
		}

		[XmlIgnore]
		private string _orderperson;
		
		[XmlElement(ElementName="orderperson",IsNullable=false,DataType="string")]
		public string orderperson
		{ 
			get { return _orderperson; }
			set { _orderperson = value; }
		}

		[XmlIgnore]
		private shipto _shipto;
		
        [XmlElement(Type=typeof(shipto),ElementName="shipto",IsNullable=false)]
		public shipto shipto
		{
			get
			{
				if (_shipto == null) _shipto = new shipto();		
				return _shipto;
			}
			set {_shipto = value;}
		}

		[XmlIgnore]
		private List<item> _item;
		
        [XmlElement(Type=typeof(item),ElementName="item",IsNullable=false)]
		public List<item> item
		{
			get
			{
				if (_item == null) _item = new List<item>();
				return _item;
			}
			set {_item = value;}
		}

		public shiporder()
		{
		}
	}


	[XmlType(TypeName="shipto"),Serializable]
	public class shipto
	{

		[XmlIgnore]
		private string _name;
		
		[XmlElement(ElementName="name",IsNullable=false,DataType="string")]
		public string name
		{ 
			get { return _name; }
			set { _name = value; }
		}

		[XmlIgnore]
		private string _address;
		
		[XmlElement(ElementName="address",IsNullable=false,DataType="string")]
		public string address
		{ 
			get { return _address; }
			set { _address = value; }
		}

		[XmlIgnore]
		private string _city;
		
		[XmlElement(ElementName="city",IsNullable=false,DataType="string")]
		public string city
		{ 
			get { return _city; }
			set { _city = value; }
		}

		[XmlIgnore]
		private string _country;
		
		[XmlElement(ElementName="country",IsNullable=false,DataType="string")]
		public string country
		{ 
			get { return _country; }
			set { _country = value; }
		}

		public shipto()
		{
		}
	}


	[XmlType(TypeName="item"),Serializable]
	public class item
	{

		[XmlIgnore]
		private string _title;
		
		[XmlElement(ElementName="title",IsNullable=false,DataType="string")]
		public string title
		{ 
			get { return _title; }
			set { _title = value; }
		}

		[XmlIgnore]
		private string _note;
		
		[XmlElement(ElementName="note",IsNullable=false,DataType="string")]
		public string note
		{ 
			get { return _note; }
			set { _note = value; }
		}

		[XmlIgnore]
		private string _quantity;
		
		[XmlElement(ElementName="quantity",IsNullable=false,DataType="positiveInteger")]
		public string quantity
		{ 
			get { return _quantity; }
			set { _quantity = value; }
		}

		[XmlIgnore]
        private decimal _price;
		
		[XmlIgnore]
		public bool _priceSpecified;
		
		
        [XmlElement(ElementName="price",IsNullable=false,DataType="decimal")]
		public decimal price
		{ 
			get { return _price; }
			set { _price = value; _priceSpecified = true; }
		}

		public item()
		{
		}
	}
}

#pragma warning restore 1591 
