#pragma warning disable 1591

// Copyright 2008, Microsoft Corporation
// Sample Code - Use restricted to terms of use defined in the accompanying license agreement (EULA.doc)

//--------------------------------------------------------------
// Autogenerated by XSDObjectGen version 2.0.0.0
// Schema file: schema.xsd
// Creation Date: 3/9/2019 18:49:43
//--------------------------------------------------------------

#include <iostream>
#include <string>
#include <ctime>

namespace Test
{

	struct Declarations
	{
		const std::string SchemaVersion = "";
	}




	struct shipto
	{

		
		std::string _name;
		

		
		std::string _address;
		

		
		std::string _city;
		

		
		std::string _country;
		

		 shipto()
		{
		}
	}


	struct item
	{

		
		std::string _title;
		

		
		std::string _note;
		

		
		std::string _quantity;
		

		
        int _price;
        

		 item()
		{
		}
	}


	struct shiporder
	{

		
		std::string _orderid;
		

		
		std::string _orderperson;
		

		
		Test.shipto _shipto;
		

		
		std::vector<Test.item> _item;
		

		 shiporder()
		{
		}
	}
}

#pragma warning restore 1591 
